config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get 'tags/:tag', to: 'tags#show', as: :tag

  resources :posts do
    resources :comments, except: [:index, :show]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  acts_as_taggable

  validates :content, presence: true
  validates :title, presence: true
  validates :author, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html {redirect_to post_path(@post)}
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to post_path(@post)}
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :author, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @posts = Post.tagged_with(params[:tag])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div id="new_comment_form">
  <%= form_for [@post, @comment], remote: true do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content, cols: 40, rows: 5  %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <br>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#new_comment_form').remove();
$('#new_comment_link').show();
$('#comments').append('<li id="comment_<%= @comment.id %>"><%= @comment.content %>, by <%= @comment.user.username %> - <%= distance_of_time_in_words(@comment.created_at, Time.now) %> ago <%= link_to "Edit", edit_post_comment_path(@post, @comment) %> | <%= link_to "Delete", post_comment_path(@post, @comment), method: "delete", remote: true %></li>');

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Add a Comment to "<%= @post.title %>"</h1>

<%= render "form" %>

app/views/comments/new.js.erb
$('#new_comment_link').hide().after('<%= j render "form" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= link_to "Home", root_path %> |
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.username %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content, cols: 40, rows: 10  %>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Blog</h1>

<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %>, by <%= post.author %>
    <ul>
      <li><%= truncate(post.content, length: 100, separator: ' ') %></li>
    </ul>
    Tags: <%= raw post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %>
  </li>
  <% end %>
</ul>
<% if current_user && current_user.admin? %>
<%= link_to "Add a Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>Add a Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3>by <%= @post.author %>, <%= distance_of_time_in_words(@post.created_at, Time.now) %> ago</h3>

<p><%= @post.content %></p>
<p>Tags: <%= raw @post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %></p>
<% if current_user && current_user.admin? %>
<%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to "Delete", post_path(@post, @comment), method: "delete" %>
<% end %>
<hr>

<h3>Comments</h3>
<% if current_user %>
<%= link_to "Add a comment", new_post_comment_path(@post), id: "new_comment_link", remote: true %>
<% end %>

<ul id="comments">
  <% @post.comments.each do |comment| %>
  <li><%= comment.content %>, by <%= comment.user.username %> - <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago
  <% if current_user == comment.user || current_user && current_user.admin? %>
    <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
    <%= link_to "Delete", post_comment_path(@post, comment), method: "delete" %>
  <% end %>
  </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>